<Project>
  <PropertyGroup>
    <!-- The OpenHarmony app model uses a NAPI/.hap host, not a classic apphost. -->
    <UseAppHost Condition=" '$(UseAppHost)' == '' ">false</UseAppHost>
    <SelfContained Condition=" '$(SelfContained)' == '' ">true</SelfContained>
    <AllowSelfContainedWithoutRuntimeIdentifier Condition=" '$(AllowSelfContainedWithoutRuntimeIdentifier)' == '' ">true</AllowSelfContainedWithoutRuntimeIdentifier>
    <GenerateDependencyFile Condition=" '$(GenerateDependencyFile)' == '' ">false</GenerateDependencyFile>
    <CopyLocalLockFileAssemblies Condition=" '$(CopyLocalLockFileAssemblies)' == '' ">true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
</Project>
