<Project>
  <!-- Version-only TargetFramework: this file is only imported for openharmony TFMs. -->
  <ItemGroup>
    <KnownFrameworkReference Include="Microsoft.OpenHarmony"
                              TargetFramework="net11.0"
                              RuntimeFrameworkName="Microsoft.OpenHarmony"
                              DefaultRuntimeFrameworkVersion="1.0.0-preview.23"
                              LatestRuntimeFrameworkVersion="1.0.0-preview.23"
                              TargetingPackName="Microsoft.OpenHarmony.Ref.$(TargetPlatformVersion)"
                              TargetingPackVersion="1.0.0-preview.23"
                              RuntimePackNamePatterns="Microsoft.OpenHarmony.Runtime.$(TargetPlatformVersion).**RID**"
                              RuntimePackRuntimeIdentifiers="openharmony-arm64"
                              />
  </ItemGroup>
</Project>
